const data = {
  canada: 'canada',
  ny: 'ny',
  'ciudad sandino': 'ciudad sandino',
  jinxiu: 'jinxiu',
  'ash shuhada': 'ash shuhada',
  zhongzhai: 'zhongzhai',
  foundiougne: 'foundiougne',
  'sekongkang bawah': 'sekongkang bawah',
  nangalisan: 'nangalisan',
  nankou: 'nankou',
  maiami: 'maiami',
  'san rafael del sur': 'san rafael del sur',
  'vicente guerrero': 'vicente guerrero',
  chemerivtsi: 'chemerivtsi',
  ordynskoye: 'ordynskoye',
  yashalta: 'yashalta',
  polevskoy: 'polevskoy',
  krasnogorskiy: 'krasnogorskiy',
  ifo: 'ifo',
  amiens: 'amiens',
  tororo: 'tororo',
  cabinda: 'cabinda',
  kilifi: 'kilifi',
  banyo: 'banyo',
  kotlovka: 'kotlovka',
  kopstal: 'kopstal',
  putukrejo: 'putukrejo',
  xitieshan: 'xitieshan',
  dagupan: 'dagupan',
  'las flores': 'las flores',
  hobaramachi: 'hobaramachi',
  chayek: 'chayek',
  'inabaan sur': 'inabaan sur',
  eskilstuna: 'eskilstuna',
  vailoatai: 'vailoatai',
  cungking: 'cungking',
  montlucon: 'montlucon',
  'ali al gharbi': 'ali al gharbi',
  kelburn: 'kelburn',
  miami: 'miami',
  yanagawa: 'yanagawa',
  'san pedro': 'san pedro',
  vyshhorod: 'vyshhorod',
  sydney: 'sydney',
  mukhen: 'mukhen',
  jiexiu: 'jiexiu',
  shimorskoye: 'shimorskoye',
  shorapani: 'shorapani',
  paratinga: 'paratinga',
  faisalabad: 'faisalabad',
  'chum phae': 'chum phae',
  macayug: 'macayug',
  portez: 'portez',
  changning: 'changning',
  kalipucang: 'kalipucang' }

module.exports.data = data;
